### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by yukaputz** [jingnanshi/KickassScrapper#3]
Have install on ubuntu 14.04 headless server.  When I run kickass-get (someterm) I get kicked backed that I need at least python 2.7.9 and my version is 2.7.6 although I have 3.4 installed as well.  How do I launch the command with the correct python version?

**Comment by jingnanshi** [comment]
Hi, sorry but right now the script only supports Python 2.7.9 +. The reason for that is this one: http://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning 

You can disable the version check by go to kickass_parse.py and comment out the sys.exit() on line 9.

**Comment by yukaputz** [comment]
Please excuse my ignorance, this all new for me.  So if I disable the version check it will run under 2.7.6?   If I install and compile 2.7.9 on my machine, how would I launch kickass-get under the correct version of python?  the default will still be 2.7.6.  And really, thank you for the work you have done on this, the idea of accessing kickass without all the excess garbage is a fantastic idea.

**Comment by jingnanshi** [comment]
Hi, so if you disable the version check, you can run the script in 2.7.6, but it may encounter some bugs. 

If you install and compile 2.7.9, to let kickass-get run in this new environment, you probably need to change your path variable. See step 1 in this post: https://linuxconfig.org/how-to-change-from-default-to-alternative-python-version-on-debian-linux It's about Debian, but it should also work on Ubuntu.

Thank you for your appreciation of this project. Torrent hoarding is the best.

**Comment by yukaputz** [comment]
Hate to keep pestering you about this but this is what i have run into.  Any further wisdom?  For what its worth I can get piratebay-get to work no problems.  My hangup seems to be this python issue.

**Changing alias in bash file yields**

### 

yukaputz@media-1:~$ python -V
Python 3.4.3
yukaputz@media-1:~$ 
yukaputz@media-1:~$ kickass-get
At least python 2.7.9 required. Your version is 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2

**Commenting out Line 9 yields**

yukaputz@media-1:~$ kickass-get test
[GCC 4.8.2]
Checking connection at http://kat.cr.
Connection at http://kat.cr succeeded.
Retriving page at http://kat.cr/usearch/test category:movies.
Traceback (most recent call last):
  File "/usr/local/bin/kickass-get", line 9, in <module>
    load_entry_point('kickass-get==0.2.2', 'console_scripts', 'kickass-get')()
  File "/usr/local/lib/python2.7/dist-packages/kickass/kickass_parse.py", line 381, in main
    page_torrents_traverser(command_line.parse_args())
  File "/usr/local/lib/python2.7/dist-packages/kickass/kickass_parse.py", line 158, in page_torrents_traverser
    page_links = get_page_torrent_links(index_url, root_url)
  File "/usr/local/lib/python2.7/dist-packages/kickass/kickass_parse.py", line 55, in get_page_torrent_links
    response = requests.get(page_url)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 55, in get
    return request('get', url, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 44, in request
    return session.request(method=method, url=url, *_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests_cache/core.py", line 128, in request
    *_kwargs
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 455, in request
    resp = self.send(prep, *_send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests_cache/core.py", line 101, in send
    return send_request_and_cache_response()
  File "/usr/local/lib/python2.7/dist-packages/requests_cache/core.py", line 93, in send_request_and_cache_response
    response = super(CachedSession, self).send(request, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 578, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 178, in resolve_redirects
    allow_redirects=False,
  File "/usr/local/lib/python2.7/dist-packages/requests_cache/core.py", line 101, in send
    return send_request_and_cache_response()
  File "/usr/local/lib/python2.7/dist-packages/requests_cache/core.py", line 93, in send_request_and_cache_response
    response = super(CachedSession, self).send(request, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 558, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 385, in send
    raise SSLError(e)
requests.exceptions.SSLError: [Errno 1] _ssl.c:510: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
yukaputz@media-1:

**Comment by jingnanshi** [comment]
Hi, did you install kickass-get using pip?

**Comment by yukaputz** [comment]
yup.

**Comment by jingnanshi** [comment]
I just committed a new kickass_parse.py file with a workaround.

Get the new kickass_parse.py, and change line

VERIFY = True;

to VERIFY = False;

That should solve the SSL problem.

**Comment by jingnanshi** [comment]
Another way to solve this problem:
1. Install a new Python environment of Python 2.7.9: https://wwken.wordpress.com/2015/05/02/how-to-change-default-python-version-in-ubuntu-using-virtualenv/
2. Install pip on the new Python 2.7.9 environment. EDIT: virtualenv already has pip, so you don't need to install pip again.
3. Install kickass-get using the new pip
4. That should do the trick.

**Comment by yukaputz** [comment]
**No Joy.  I ran the following**
sudo pip install kickass-get --upgrade (worked fine)
sudo nano /usr/local/lib/python2.7/dist-packages/kickass/kickass_parse.py
**But VERIFY = False was not found even with a search, tried just verify, still not found**  :-(

**Comment by yukaputz** [comment]
Ok, I'll give your alternate solution a whirl.  :-)

**Comment by jingnanshi** [comment]
Oops, I didn't uploaded it to PyPi... I only uploaded to Github. Wait a minute.

**Comment by jingnanshi** [comment]
I just uploaded to PyPi.

Anyway, my alternative solution should be the best, because the VERIFY=False is essentially skipping the SSL certificate part, which is unsafe.

**Comment by yukaputz** [comment]
Ok, I'll try again.  

Oh  I had seen that article about using env before and tried it before contacting you.  When I run it...well take a look.  I contacted the author for his input as well.  I'm such a python boob.  

yukaputz@media-1:~/projects/Python-2.7.9$ ./configure –prefix /usr/local/lib/python2.7.9
configure: WARNING: you should use --build, --host, --target
configure: WARNING: invalid host type: –prefix
configure: WARNING: you should use --build, --host, --target
configure: WARNING: invalid host type: /usr/local/lib/python2.7.9
checking build system type... Invalid configuration `–prefix': machine`–prefix' not recognized

**Comment by jingnanshi** [comment]
Well, if everything fails, you can always just download the Github repo to your Ubuntu, and run the kickass_parse.py using python2.7.9

Python version is annoying sometimes.

**Comment by yukaputz** [comment]
**Doesn't like Verify = False?**

yukaputz@media-1:~$ kickass-get test

At least python 2.7.9 required for best performance. Your version is 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2]
Traceback (most recent call last):
  File "/usr/local/bin/kickass-get", line 9, in <module>
    load_entry_point('kickass-get==0.2.3', 'console_scripts', 'kickass-get')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 351, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2363, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2088, in load
    entry = **import**(self.module_name, globals(),globals(), ['**name**'])
  File "/usr/local/lib/python2.7/dist-packages/kickass/kickass_parse.py", line 30, in <module>
    VERIFY = FALSE;
NameError: name 'FALSE' is not define

**Comment by jingnanshi** [comment]
Use False, with only F in capital

**Comment by yukaputz** [comment]
BADABING!  That worked.

**Comment by jingnanshi** [comment]
Awesome! Glad I can help. Let me know if you have further questions : )

**Comment by yukaputz** [comment]
Thanks again for your help!!!!

**Comment by jingnanshi** [comment]
No problem
